apiVersion: v1
kind: Secret
metadata:
  name: iceberg-catalog-mysql
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.iceberg.catalogMysql.rootPassword | quote }}
  mysql-password: {{ .Values.iceberg.catalogMysql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-rest-catalog-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  jdbc-user: "iceberg"
  jdbc-password: {{ .Values.iceberg.catalogMysql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-smt-mysql
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.kafkaConnect.smt.jdbcPassword | quote }}
