apiVersion: v1
kind: Secret
metadata:
  name: iceberg-catalog-mysql
  namespace: duckdb
type: Opaque
stringData:
  mysql-root-password: "cre6630IcebergRootDuckdb2026!"
  mysql-password: "cre6630IcebergDuckdb2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-rest-catalog-secret
  namespace: duckdb
type: Opaque
stringData:
  jdbc-user: "iceberg"
  jdbc-password: "cre6630IcebergDuckdb2026!"
---
apiVersion: v1
kind: Secret
metadata:
  name: iceberg-smt-mysql
  namespace: duckdb
type: Opaque
stringData:
  password: "password"
